# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestMainWindow(object):
    def setupUi(self, TestMainWindow):
        TestMainWindow.setObjectName("TestMainWindow")
        TestMainWindow.resize(675, 499)
        self.close_btn = QtWidgets.QPushButton(TestMainWindow)
        self.close_btn.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.close_btn.setObjectName("close_btn")

        self.retranslateUi(TestMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TestMainWindow)

    def retranslateUi(self, TestMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TestMainWindow.setWindowTitle(_translate("TestMainWindow", "kahlid测试中英文"))
        self.close_btn.setText(_translate("TestMainWindow", "关闭"))
